In [4]:
import pandas as pd

items_data_dir = r"C:\Users\A1134913\Projects\Personal\ProjectIdeas\Projects\CraveAI-HybridSearchWithReranker\search\data\items.csv"
res_data_dir = r"C:\Users\A1134913\Projects\Personal\ProjectIdeas\Projects\CraveAI-HybridSearchWithReranker\search\data\items.csv"

item_data = pd.read_csv(items_data_dir)
res_data = pd.read_csv(res_data_dir)

item_data[:10]

# item_data[:10]["item_name"]

,item_id,restaurant_id,item_name,item_description,item_rating,item_type,cuisine
0,ITEM_000001,REST_005755,Authentic Kung Pao Chicken,Sichuan-style stir-fried diced chicken with cr...,4.6,Non-Veg,Chinese
1,ITEM_000002,REST_003552,Malabar Fish Curry,Seer fish fillets gently simmered in coconut m...,4.3,Non-Veg,Kerala
2,ITEM_000003,REST_005963,Baja Style Fish Tacos,Crisp beer-battered white fish in soft warm co...,4.3,Non-Veg,Mexican
3,ITEM_000004,REST_007924,Smoked Texas BBQ Brisket,Slow-smoked prime beef brisket with oakwood ba...,3.9,Non-Veg,American
4,ITEM_000005,REST_002757,Crispy Fried Chicken Burger,Buttermilk-brined crispy fried chicken thigh t...,4.6,Non-Veg,American
5,ITEM_000006,REST_005904,Masala Dosa,Golden crisp fermented rice-black gram crepe s...,3.7,Veg,South Indian
6,ITEM_000007,REST_009760,House Special Medu Vada Sambhar Combo,Crispy deep-fried lentil donuts served submerg...,3.2,Veg,South Indian
7,ITEM_000008,REST_009430,Greek Spanakopita,Flaky golden phyllo pastry stuffed with sautée...,3.2,Veg,Mediterranean
8,ITEM_000009,REST_004458,Palak Paneer,Fresh paneer blocks infused in seasoned blanch...,3.3,Veg,North Indian
9,ITEM_000010,REST_003948,Greek Spanakopita,Flaky golden phyllo pastry stuffed with sautée...,3.5,Veg,Mediterranean

In [3]:
import pandas as pd

query_data = pd.read_csv(r"C:\Users\A1134913\Projects\Personal\ai-inference-roadmap\CraveAI\data\user_queries_with_history_and_clicks.csv")

query_data[:50]

,user_id,query_id,query_string,num_returned_items,response_item_ids,response_restaurant_ids,user_order_history,clicked_item_ids,ordered_item_id
0,USR_2824,Q_000001,sweet rich vegetarian north indian paneer gravy,618,"[""ITEM_000008"", ""ITEM_000011"", ""ITEM_000015"", ...","[""REST_001771"", ""REST_006986"", ""REST_003788"", ...","[""ITEM_005989"", ""ITEM_004265"", ""ITEM_000302"", ...","[""ITEM_002374"", ""ITEM_001469""]",ITEM_002374
1,USR_2535,Q_000002,spicy dry chicken with black pepper and curry ...,303,"[""ITEM_000031"", ""ITEM_000045"", ""ITEM_000049"", ...","[""REST_008820"", ""REST_004823"", ""REST_001299"", ...","[""ITEM_007765"", ""ITEM_004806"", ""ITEM_000131"", ...","[""ITEM_000430"", ""ITEM_007323"", ""ITEM_004152""]",ITEM_000430
2,USR_7924,Q_000003,schezwan wok tossed fried noodles,151,"[""ITEM_000018"", ""ITEM_000054"", ""ITEM_000099"", ...","[""REST_001052"", ""REST_009890"", ""REST_000168"", ...","[""ITEM_001812"", ""ITEM_006740"", ""ITEM_006465"", ...","[""ITEM_005324"", ""ITEM_005930""]",ITEM_005324
3,USR_1711,Q_000004,cottage cheese in vibrant green spinach curry,110,"[""ITEM_000150"", ""ITEM_000189"", ""ITEM_000284"", ...","[""REST_006691"", ""REST_009662"", ""REST_002463"", ...","[""ITEM_008448"", ""ITEM_006415"", ""ITEM_006307"", ...","[""ITEM_004371"", ""ITEM_003423""]",ITEM_004371
4,USR_6925,Q_000005,sourdough bread with avocado smash and cherry ...,62,"[""ITEM_000190"", ""ITEM_000215"", ""ITEM_000384"", ...","[""REST_004393"", ""REST_002709"", ""REST_007342"", ...","[""ITEM_004389"", ""ITEM_001873"", ""ITEM_006600"", ...","[""ITEM_000384"", ""ITEM_002404"", ""ITEM_000679""]",ITEM_000384
5,USR_8428,Q_000006,coconut basil curry veg with bamboo shoots and...,118,"[""ITEM_000039"", ""ITEM_000043"", ""ITEM_000230"", ...","[""REST_007795"", ""REST_003984"", ""REST_004181"", ...","[""ITEM_001271"", ""ITEM_003128"", ""ITEM_009792"", ...","[""ITEM_003471"", ""ITEM_002326"", ""ITEM_007485""]",ITEM_003471
6,USR_3677,Q_000007,egg pasta ribbons tossed in creamy forest mush...,451,"[""ITEM_000025"", ""ITEM_000044"", ""ITEM_000046"", ...","[""REST_006422"", ""REST_005493"", ""REST_004228"", ...","[""ITEM_000930"", ""ITEM_003365"", ""ITEM_000531"", ...","[""ITEM_007700"", ""ITEM_003775"", ""ITEM_009677""]",ITEM_007700
7,USR_7572,Q_000008,vegan meat alternative jackfruit biryani,220,"[""ITEM_000041"", ""ITEM_000103"", ""ITEM_000108"", ...","[""REST_009079"", ""REST_008040"", ""REST_005163"", ...","[""ITEM_008330"", ""ITEM_002586"", ""ITEM_004692"", ...","[""ITEM_006234"", ""ITEM_007215"", ""ITEM_005539"", ...",ITEM_006234
8,USR_5040,Q_000009,spinach cottage cheese curry north indian style,110,"[""ITEM_000150"", ""ITEM_000189"", ""ITEM_000284"", ...","[""REST_006691"", ""REST_009662"", ""REST_002463"", ...","[""ITEM_000906"", ""ITEM_007670"", ""ITEM_000450"", ...","[""ITEM_004907"", ""ITEM_002765"", ""ITEM_001902"", ...",ITEM_004907
9,USR_2796,Q_000010,fermented rice lentil crepe with potato mash a...,99,"[""ITEM_000123"", ""ITEM_000130"", ""ITEM_000178"", ...","[""REST_009637"", ""REST_009528"", ""REST_006397"", ...","[""ITEM_009227"", ""ITEM_004305"", ""ITEM_009712"", ...","[""ITEM_008863"", ""ITEM_000692"", ""ITEM_004959"", ...",ITEM_008863
10,USR_2876,Q_000011,authentic tom yum goong seafood soup,95,"[""ITEM_000078"", ""ITEM_000141"", ""ITEM_000196"", ...","[""REST_008487"", ""REST_000929"", ""REST_002668"", ...","[""ITEM_002827"", ""ITEM_008270"", ""ITEM_000072"", ...","[""ITEM_003703"", ""ITEM_004864""]",ITEM_003703
11,USR_9201,Q_000012,medu vada with sambhar and coconut chutney,104,"[""ITEM_000131"", ""ITEM_000159"", ""ITEM_000169"", ...","[""REST_003791"", ""REST_000257"", ""REST_009447"", ...","[""ITEM_002665"", ""ITEM_006484"", ""ITEM_002726"", ...","[""ITEM_001148"", ""ITEM_005651"", ""ITEM_007630"", ...",ITEM_001148
12,USR_9689,Q_000013,mild cottage cheese curry with butter and naan,618,"[""ITEM_000008"", ""ITEM_000011"", ""ITEM_000015"", ...","[""REST_001771"", ""REST_006986"", ""REST_003788"", ...","[""ITEM_009034"", ""ITEM_005778"", ""ITEM_009735"", ...","[""ITEM_001907"", ""ITEM_004133"", ""ITEM_001010"", ...",ITEM_001907
13,USR_2403,Q_000014,cottage cheese in vibrant green spinach curry,110,"[""ITEM_000150"", ""ITEM_000189"", ""ITEM_000284"", ...","[""REST_006691"", ""REST_009662"", ""REST_002463"", ...","[""ITEM_009735"", ""ITEM_005585"", ""ITEM_001617"", ...","[""ITEM_008601"", ""ITEM_007961"", ""ITEM_005374""]",ITEM_008601
14,USR_9645,Q_000015,healthy middle eastern falafel and hummus plate,297,"[""ITEM_000004"", ""ITEM_000063"", ""ITEM_000117"", ...","[""REST_003551"", ""REST_006869"", ""REST_008970"", ...","[""ITEM_007841"", ""ITEM_009229"", ""ITEM_007978"", ...","[""ITEM_009345"", ""ITEM_006613"", ""ITEM_006145""]",ITEM_009345
15,USR_5061,Q_000016,fragrant royal mutton biryani with long grain ...,113,"[""ITEM_000042"", ""ITEM_000055"", ""ITEM_000209"", ...","[""REST_005055"", ""REST_006093"", ""REST_006659"", ...","[""ITEM_001378"", ""ITEM_001194"", ""ITEM_003941"", ...","[""ITEM_008094"", ""ITEM_002846"", ""ITEM_000042""]",ITEM_008094
16,USR_1514,Q_000017,authentic chickpea fritters with olive oil dip...,297,"[""ITEM_000004"", ""ITEM_000063"", ""ITEM_000117"", ...","[""REST_003551"", ""REST_006869"", ""REST_008970"", ...","[""ITEM_008327"", ""ITEM_004339"", ""ITEM_007174"", ...","[""ITEM_004058"", ""ITEM_003607"", ""ITEM_009345"", ...",ITEM_004058
17,USR_2545,Q_000018,aromatic authentic kashmiri mutton curry,176,"[""ITEM_000059"", ""ITEM_000094"", ""ITEM_000096"", ...","[""REST_001738"", ""REST_002693"", ""REST_009984"", ...","[""ITEM_001010"", ""ITEM_000580"", ""ITEM_004068"", ...","[""ITEM_005396"", ""ITEM_000607"", ""ITEM_009611"", ...",ITEM_005396
18,USR_6559,Q_000019,pan fried japanese chicken dumplings with sesa...,126,"[""ITEM_000009"", ""ITEM_000090"", ""ITEM_000093"", ...","[""REST_000320"", ""REST_000040"", ""REST_005749"", ...","[""ITEM_004668"", ""ITEM_001026"", ""ITEM_007754"", ...","[""ITEM_001591"", ""ITEM_003845"", ""ITEM_001385"", ...",ITEM_001591
19,USR_2604,Q_000020,charcoal roasted chicken pieces in satin butte...,227,"[""ITEM_000057"", ""ITEM_000112"", ""ITEM_000129"", ...","[""REST_005678"", ""REST_005874"", ""REST_003734"", ...","[""ITEM_008682"", ""ITEM_002385"", ""ITEM_001635"", ...","[""ITEM_009234"", ""ITEM_008127""]",ITEM_009234
20,USR_8956,Q_000021,mexican soft corn tortilla fish wrap,308,"[""ITEM_000016"", ""ITEM_000026"", ""ITEM_000047"", ...","[""REST_003668"", ""REST_006367"", ""REST_000417"", ...","[""ITEM_004308"", ""ITEM_007480"", ""ITEM_004699"", ...","[""ITEM_001031"", ""ITEM_000026"", ""ITEM_006681""]",ITEM_001031
21,USR_8973,Q_000022,south indian breakfast fermented crepe with sa...,99,"[""ITEM_000123"", ""ITEM_000130"", ""ITEM_000178"", ...","[""REST_009637"", ""REST_009528"", ""REST_006397"", ...","[""ITEM_001020"", ""ITEM_000898"", ""ITEM_008292"", ...","[""ITEM_000645"", ""ITEM_003872""]",ITEM_000645
22,USR_9701,Q_000023,clarified butter roasted crepe,173,"[""ITEM_000098"", ""ITEM_000251"", ""ITEM_000309"", ...","[""REST_003313"", ""REST_005801"", ""REST_001965"", ...","[""ITEM_003982"", ""ITEM_007058"", ""ITEM_002135"", ...","[""ITEM_001497"", ""ITEM_008681"", ""ITEM_009935""]",ITEM_001497
23,USR_1651,Q_000024,authentic italian dessert with mascarpone and ...,295,"[""ITEM_000061"", ""ITEM_000138"", ""ITEM_000155"", ...","[""REST_009610"", ""REST_001161"", ""REST_000387"", ...","[""ITEM_003924"", ""ITEM_005783"", ""ITEM_002036"", ...","[""ITEM_009851"", ""ITEM_003828"", ""ITEM_005783"", ...",ITEM_009851
24,USR_5915,Q_000025,porcini mushroom fettuccine in white wine crea...,451,"[""ITEM_000025"", ""ITEM_000044"", ""ITEM_000046"", ...","[""REST_006422"", ""REST_005493"", ""REST_004228"", ...","[""ITEM_008203"", ""ITEM_001645"", ""ITEM_001192"", ...","[""ITEM_000932"", ""ITEM_007280""]",ITEM_000932
25,USR_4492,Q_000026,juicy american beef burgur with pickles,581,"[""ITEM_000106"", ""ITEM_000146"", ""ITEM_000154"", ...","[""REST_001387"", ""REST_001610"", ""REST_001484"", ...","[""ITEM_003415"", ""ITEM_001828"", ""ITEM_005381"", ...","[""ITEM_006454"", ""ITEM_006718""]",ITEM_006454
26,USR_9900,Q_000027,authentic ramen with chashu chicken and spring...,213,"[""ITEM_000024"", ""ITEM_000113"", ""ITEM_000143"", ...","[""REST_002030"", ""REST_002053"", ""REST_005931"", ...","[""ITEM_009640"", ""ITEM_005306"", ""ITEM_001440"", ...","[""ITEM_009536"", ""ITEM_009726""]",ITEM_009536
27,USR_5333,Q_000028,kashmiri spiced mutton curry,176,"[""ITEM_000059"", ""ITEM_000094"", ""ITEM_000096"", ...","[""REST_001738"", ""REST_002693"", ""REST_009984"", ...","[""ITEM_002039"", ""ITEM_006998"", ""ITEM_006489"", ...","[""ITEM_001846"", ""ITEM_008682"", ""ITEM_002902"", ...",ITEM_001846
28,USR_5325,Q_000029,twin seared beef patties with special relish a...,581,"[""ITEM_000106"", ""ITEM_000146"", ""ITEM_000154"", ...","[""REST_001387"", ""REST_001610"", ""REST_001484"", ...","[""ITEM_000718"", ""ITEM_000187"", ""ITEM_005834"", ...","[""ITEM_000945"", ""ITEM_005145""]",ITEM_000945
29,USR_5291,Q_000030,traditional ghee roast fermented savory crepe,173,"[""ITEM_000098"", ""ITEM_000251"", ""ITEM_000309"", ...","[""REST_003313"", ""REST_005801"", ""REST_001965"", ...","[""ITEM_002620"", ""ITEM_009551"", ""ITEM_000636"", ...","[""ITEM_006036"", ""ITEM_001322""]",ITEM_006036
30,USR_3426,Q_000031,authentic italian thin crust pizza with buffal...,54,"[""ITEM_000305"", ""ITEM_000530"", ""ITEM_000659"", ...","[""REST_002923"", ""REST_009697"", ""REST_008684"", ...","[""ITEM_009851"", ""ITEM_003696"", ""ITEM_009610"", ...","[""ITEM_002969"", ""ITEM_001995""]",ITEM_002969
31,USR_6794,Q_000032,steamed or fried lentil combo with sambar,104,"[""ITEM_000131"", ""ITEM_000159"", ""ITEM_000169"", ...","[""REST_003791"", ""REST_000257"", ""REST_009447"", ...","[""ITEM_003017"", ""ITEM_007274"", ""ITEM_000435"", ...","[""ITEM_008955"", ""ITEM_001467"", ""ITEM_009748""]",ITEM_008955
32,USR_6442,Q_000033,steamed and pan seared chicken gyoza,126,"[""ITEM_000009"", ""ITEM_000090"", ""ITEM_000093"", ...","[""REST_000320"", ""REST_000040"", ""REST_005749"", ...","[""ITEM_001582"", ""ITEM_006822"", ""ITEM_000506"", ...","[""ITEM_008481"", ""ITEM_001266"", ""ITEM_007787""]",ITEM_008481
33,USR_4644,Q_000034,pan seared chicken tossed with fresh crushed b...,303,"[""ITEM_000031"", ""ITEM_000045"", ""ITEM_000049"", ...","[""REST_008820"", ""REST_004823"", ""REST_001299"", ...","[""ITEM_005640"", ""ITEM_004817"", ""ITEM_001210"", ...","[""ITEM_004290"", ""ITEM_003693"", ""ITEM_007113""]",ITEM_004290
34,USR_6753,Q_000035,aromatic coconut thai curry with sweet basil,118,"[""ITEM_000039"", ""ITEM_000043"", ""ITEM_000230"", ...","[""REST_007795"", ""REST_003984"", ""REST_004181"", ...","[""ITEM_003259"", ""ITEM_004898"", ""ITEM_000600"", ...","[""ITEM_008714"", ""ITEM_000966"", ""ITEM_009144"", ...",ITEM_008714
35,USR_8119,Q_000036,spicy chinese chicken with dried red pepper,100,"[""ITEM_000013"", ""ITEM_000191"", ""ITEM_000194"", ...","[""REST_009591"", ""REST_006350"", ""REST_009811"", ...","[""ITEM_003406"", ""ITEM_004614"", ""ITEM_000862"", ...","[""ITEM_006798"", ""ITEM_007526""]",ITEM_006798
36,USR_1027,Q_000037,classic double smash burger with melted cheese,581,"[""ITEM_000106"", ""ITEM_000146"", ""ITEM_000154"", ...","[""REST_001387"", ""REST_001610"", ""REST_001484"", ...","[""ITEM_002509"", ""ITEM_005193"", ""ITEM_009132"", ...","[""ITEM_003861"", ""ITEM_001446"", ""ITEM_006132"", ...",ITEM_003861
37,USR_7691,Q_000038,wok charred noodles with crunchy julienned veg...,151,"[""ITEM_000018"", ""ITEM_000054"", ""ITEM_000099"", ...","[""REST_001052"", ""REST_009890"", ""REST_000168"", ...","[""ITEM_003195"", ""ITEM_005508"", ""ITEM_007526"", ...","[""ITEM_009288"", ""ITEM_006566"", ""ITEM_005930""]",ITEM_009288
38,USR_5978,Q_000039,kerala style tamarind seer fish curry,107,"[""ITEM_000133"", ""ITEM_000152"", ""ITEM_000248"", ...","[""REST_001224"", ""REST_007302"", ""REST_005838"", ...","[""ITEM_009191"", ""ITEM_008425"", ""ITEM_002918"", ...","[""ITEM_006953"", ""ITEM_005852"", ""ITEM_007962"", ...",ITEM_006953
39,USR_5649,Q_000040,classic double smash burger with melted cheese,581,"[""ITEM_000106"", ""ITEM_000146"", ""ITEM_000154"", ...","[""REST_001387"", ""REST_001610"", ""REST_001484"", ...","[""ITEM_000570"", ""ITEM_002882"", ""ITEM_005953"", ...","[""ITEM_004576"", ""ITEM_003900"", ""ITEM_002946"", ...",ITEM_004576
40,USR_2193,Q_000041,egg pasta ribbons tossed in creamy forest mush...,451,"[""ITEM_000025"", ""ITEM_000044"", ""ITEM_000046"", ...","[""REST_006422"", ""REST_005493"", ""REST_004228"", ...","[""ITEM_007294"", ""ITEM_005828"", ""ITEM_003624"", ...","[""ITEM_006542"", ""ITEM_008132"", ""ITEM_004394""]",ITEM_006542
41,USR_1090,Q_000042,flaky phyllo pastry stuffed with spinach and feta,108,"[""ITEM_000010"", ""ITEM_000037"", ""ITEM_000176"", ...","[""REST_003948"", ""REST_008196"", ""REST_005410"", ...","[""ITEM_008188"", ""ITEM_000810"", ""ITEM_009905"", ...","[""ITEM_003078"", ""ITEM_008139"", ""ITEM_006295""]",ITEM_003078
42,USR_2988,Q_000043,creamy truffle pasta with parmesan,451,"[""ITEM_000025"", ""ITEM_000044"", ""ITEM_000046"", ...","[""REST_006422"", ""REST_005493"", ""REST_004228"", ...","[""ITEM_007483"", ""ITEM_006223"", ""ITEM_008016"", ...","[""ITEM_007916"", ""ITEM_005277"", ""ITEM_007160"", ...",ITEM_007916
43,USR_3607,Q_000044,cottage cheese in vibrant green spinach curry,110,"[""ITEM_000150"", ""ITEM_000189"", ""ITEM_000284"", ...","[""REST_006691"", ""REST_009662"", ""REST_002463"", ...","[""ITEM_007815"", ""ITEM_007926"", ""ITEM_005296"", ...","[""ITEM_008461"", ""ITEM_007577"", ""ITEM_003397""]",ITEM_008461
44,USR_4919,Q_000045,young raw jackfruit marinated in curd and whol...,220,"[""ITEM_000041"", ""ITEM_000103"", ""ITEM_000108"", ...","[""REST_009079"", ""REST_008040"", ""REST_005163"", ...","[""ITEM_009562"", ""ITEM_001572"", ""ITEM_002475"", ...","[""ITEM_003449"", ""ITEM_003814"", ""ITEM_003668""]",ITEM_003449
45,USR_4788,Q_000046,vegetarian edamame dim sums,239,"[""ITEM_000083"", ""ITEM_000111"", ""ITEM_000140"", ...","[""REST_003323"", ""REST_005975"", ""REST_004136"", ...","[""ITEM_001152"", ""ITEM_003585"", ""ITEM_007249"", ...","[""ITEM_000943"", ""ITEM_003680"", ""ITEM_005917"", ...",ITEM_000943
46,USR_1320,Q_000047,healthy middle eastern falafel and hummus plate,297,"[""ITEM_000004"", ""ITEM_000063"", ""ITEM_000117"", ...","[""REST_003551"", ""REST_006869"", ""REST_008970"", ...","[""ITEM_003865"", ""ITEM_008567"", ""ITEM_003826"", ...","[""ITEM_005762"", ""ITEM_006941"", ""ITEM_009333"", ...",ITEM_005762
47,USR_8140,Q_000048,crispy beer battered fish tacos with chipotle ...,308,"[""ITEM_000016"", ""ITEM_000026"", ""ITEM_000047"", ...","[""REST_003668"", ""REST_006367"", ""REST_000417"", ...","[""ITEM_000420"", ""ITEM_006684"", ""ITEM_009888"", ...","[""ITEM_006886"", ""ITEM_002197"", ""ITEM_008938""]",ITEM_006886
48,USR_1444,Q_000049,traditional vegetarian slow simmered black len...,145,"[""ITEM_000053"", ""ITEM_000164"", ""ITEM_000222"", ...","[""REST_001136"", ""REST_005022"", ""REST_006527"", ...","[""ITEM_003373"", ""ITEM_002104"", ""ITEM_004643"", ...","[""ITEM_008085"", ""ITEM_004475"", ""ITEM_006829""]",ITEM_008085
49,USR_6529,Q_000050,steamed or fried lentil combo with sambar,104,"[""ITEM_000131"", ""ITEM_000159"", ""ITEM_000169"", ...","[""REST_003791"", ""REST_000257"", ""REST_009447"", ...","[""ITEM_009461"", ""ITEM_000929"", ""ITEM_006015"", ...","[""ITEM_004817"", ""ITEM_005156"", ""ITEM_000169"", ...",ITEM_004817